export type LogType =
    | 'CREATED_TICKET'
    | 'UPDATED_TICKET'
    | 'STARTED_TICKET'
    | 'FINISHED_TICKET'
    | 'COLLECTED_TICKET'
    | 'CREATED_CATEGORY'
    | 'UPDATED_CATEGORY'
    | 'DELETED_CATEGORY'
    | 'ADD_NEW_ITEM_TO_INVENTORY'
    | 'ADD_ITEM_TO_SHOPPING_LIST'
    | 'REMOVE_ITEM_FROM_SHOPPING_LIST'
    | 'USED_PART'
    | 'SOLD_ITEM'
    | 'UPDATE_ITEM_COUNT'
    | 'UPDATE_ITEM'
    | 'DAMAGED_PART'
    | 'DEFECTIVE_PART'
    | 'RETURNED_DEFECTIVE_PART'
    | 'CREATED_SELL_INVOICE'
    | 'CREATED_REPAIR_INVOICE'
    | 'CREATED_BUY_INVOICE'
    | 'CREATED_ACCESSORIES_INVOICE'
    | 'CREATED_DEPOSIT_INVOICE'
    | 'INVALIDATED_INVOICE'
    | 'CREATED_WORKER'
    | 'CREATED_CLIENT'
    | 'UPDATED_USER'
    | 'BANNED_USER'
    | 'UNBANNED_USER'
    | 'DELETED_USER'
    | 'RESTORED_USER'

export const LogType = Array(
    'CREATED_TICKET',
    'UPDATED_TICKET',
    'STARTED_TICKET',
    'FINISHED_TICKET',
    'COLLECTED_TICKET',
    'CREATED_CATEGORY',
    'UPDATED_CATEGORY',
    'DELETED_CATEGORY',
    'ADD_NEW_ITEM_TO_INVENTORY',
    'ADD_ITEM_TO_SHOPPING_LIST',
    'REMOVE_ITEM_FROM_SHOPPING_LIST',
    'USED_PART',
    'SOLD_ITEM',
    'UPDATE_ITEM_COUNT',
    'UPDATE_ITEM',
    'DAMAGED_PART',
    'DEFECTIVE_PART',
    'RETURNED_DEFECTIVE_PART',
    'CREATED_SELL_INVOICE',
    'CREATED_REPAIR_INVOICE',
    'CREATED_BUY_INVOICE',
    'CREATED_ACCESSORIES_INVOICE',
    'CREATED_DEPOSIT_INVOICE',
    'INVALIDATED_INVOICE',
    'CREATED_WORKER',
    'CREATED_CLIENT',
    'UPDATED_USER',
    'BANNED_USER',
    'UNBANNED_USER',
    'DELETED_USER',
    'RESTORED_USER'
)

export const LogTypeList = LogType.map((value, index) => ({ value, id: index }))
